[workspace]
members = [
  "./cli",
  "./ffi_lib",
  './napi',
  './napi2',
  './hello_macro',
  './use_hello_macro',
  './hello_thread',
  './hello_tokio',
  './hello_tokio_client',
]

[profile.release]
lto = true
